//! Bubblewrap sandbox helper for scanner subprocesses.
//!
//! Every scanner runs inside `bwrap` so a malicious or buggy invocation
//! can't poison follow-up jobs. Each invocation gets a fresh `/tmp`,
//! its own `$HOME`, and the worktree mounted read-only at `/workdir`.
//! `/etc` starts empty and receives only public runtime files required
//! for dynamic linking, identity lookup, name resolution, and TLS trust.
//! Network is unshared by default; LLM backends attach an explicit
//! [`SandboxNetworkConfig`] when they need isolated outbound access.
//!
//! The worker fails closed when `LOUPE_DISABLE_SANDBOX` is enabled.

use std::ffi::{OsStr, OsString};
use std::path::{Path, PathBuf};
use std::process::{ExitStatus, Stdio};

use anyhow::{Context, Result};
use clap::ValueEnum;
use serde::Deserialize;
use tokio::process::Command;

/// Path to the bwrap binary. Resolved once and cached.
const BWRAP_BIN: &str = "bwrap";

/// Public host data needed by dynamically linked agent CLIs and libc
/// identity lookups. Keep this list to individual files: mounting the
/// containing `/etc` tree would expose Loupe credentials and arbitrary
/// service configuration to repository-controlled processes.
const SANDBOX_SYSTEM_FILES: &[&str] =
	&["/etc/ld.so.cache", "/etc/passwd", "/etc/group", "/etc/nsswitch.conf"];

/// Name-resolution inputs needed only by network-enabled agent CLIs.
/// The resolver file is generated by the network launcher because the
/// slirp DNS forwarder always lives at 10.0.2.3.
const SANDBOX_NETWORK_FILES: &[&str] = &["/etc/hosts"];
pub(crate) const SANDBOX_RESOLV_CONF_PLACEHOLDER: &str = "@LOUPE_RESOLV_CONF@";

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Deserialize, ValueEnum)]
#[serde(rename_all = "kebab-case")]
pub enum SandboxNetworkMode {
	Allowlist,
	#[default]
	Public,
}

impl SandboxNetworkMode {
	pub fn as_str(self) -> &'static str {
		match self {
			Self::Allowlist => "allowlist",
			Self::Public => "public",
		}
	}
}

impl std::fmt::Display for SandboxNetworkMode {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		f.write_str(self.as_str())
	}
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SandboxNetworkConfig {
	pub mode: SandboxNetworkMode,
	pub allowlist: Vec<String>,
}

pub fn validate_network_host(host: &str) -> Result<()> {
	let host = host.trim();
	if host.is_empty() {
		anyhow::bail!("sandbox network host must not be empty");
	}
	if host.parse::<std::net::Ipv4Addr>().is_ok() {
		return Ok(());
	}
	if host.parse::<std::net::Ipv6Addr>().is_ok()
		|| host.contains(|character: char| {
			character.is_whitespace() || matches!(character, '/' | ':' | '*' | ',')
		}) {
		anyhow::bail!("invalid sandbox network hostname or IPv4 address: `{host}`");
	}
	Ok(())
}

#[derive(Debug, Clone)]
struct SandboxNetworkLaunch {
	config: SandboxNetworkConfig,
	required_hosts: Vec<String>,
}

/// Public CA locations used by the major Linux distribution families.
/// These deliberately name certificate-only paths rather than broader
/// parents such as `/etc/ssl` or `/etc/pki`, which may contain private
/// keys.
const SANDBOX_CA_PATHS: &[&str] = &[
	"/etc/ssl/certs",
	"/etc/ssl/cert.pem",
	"/etc/ca-certificates/extracted",
	"/etc/pki/ca-trust/extracted",
	"/etc/pki/tls/certs",
	"/etc/pki/tls/cert.pem",
];

/// Legacy environment variable. Enabling it is rejected because the
/// repository-controlled agent must never run with the worker's host
/// privileges.
pub const DISABLE_SANDBOX_ENV: &str = "LOUPE_DISABLE_SANDBOX";

fn ensure_sandbox_enabled(disabled: bool) -> Result<()> {
	if disabled {
		anyhow::bail!(
			"{DISABLE_SANDBOX_ENV} is not supported: LLM agents require bubblewrap isolation"
		);
	}
	Ok(())
}

/// Require a usable `bwrap` at startup. Enabling
/// `LOUPE_DISABLE_SANDBOX`, requesting a bypass through configuration,
/// or omitting bwrap is a hard startup error. Returning successfully
/// means the sandbox is available.
pub fn probe_at_startup(disabled_by_config: bool) -> Result<()> {
	ensure_sandbox_enabled(disabled_by_config || sandbox_disabled())?;
	let status = std::process::Command::new(BWRAP_BIN)
		.arg("--version")
		.stdout(Stdio::null())
		.stderr(Stdio::null())
		.status();
	match status {
		Ok(s) if s.success() => {},
		Ok(s) => anyhow::bail!("bwrap probe exited with {s}"),
		Err(e) => {
			return Err(anyhow::Error::from(e).context(format!(
			"`{BWRAP_BIN}` not found on PATH; install bubblewrap (sandbox bypass is not supported)"
		)))
		},
	}
	crate::sandbox_network::probe_network_helpers()
}

#[doc(hidden)]
pub fn run_networked_sandbox(
	mode: SandboxNetworkMode, required_hosts: Vec<String>, allow_hosts: Vec<String>,
	command: Vec<OsString>,
) -> Result<ExitStatus> {
	crate::sandbox_network::run_networked_sandbox(mode, required_hosts, allow_hosts, command)
}

/// Builder for a sandboxed `tokio::process::Command`. Default posture:
/// worktree mounted read-only at `/workdir`, fresh tmpfs `/tmp` and
/// `$HOME`, private user/process/network namespaces, `--die-with-parent`,
/// and a working directory set to neutral `/home/scanner`. The worktree remains readable at
/// `/workdir` without becoming the instruction-discovery root.
pub struct SandboxBuilder {
	workdir: PathBuf,
	network: Option<SandboxNetworkLaunch>,
	network_supervisor: Option<PathBuf>,
	disabled: bool,
	/// Caller-supplied read-only bind mounts (host path, sandbox
	/// path). Populated by [`bind_ro`] and [`allow_binary`].
	extra_ro_binds: Vec<(PathBuf, PathBuf)>,
	/// Env vars to forward into the sandbox by name (the value is
	/// looked up from the worker's own env at `build()` time).
	forward_env: Vec<&'static str>,
	/// Env vars to set to caller-provided values.
	set_env: Vec<(&'static str, OsString)>,
}

impl SandboxBuilder {
	/// New builder targeting a worktree on disk. The `workdir` is bind-
	/// mounted read-only into the sandbox at `/workdir`.
	///
	/// Always wraps. `LOUPE_DISABLE_SANDBOX` is rejected at startup by
	/// [`probe_at_startup`], so consulting it again here would only
	/// add a second, quieter way to lose isolation.
	pub fn new(workdir: impl Into<PathBuf>) -> Self {
		Self {
			workdir: workdir.into(),
			network: None,
			network_supervisor: None,
			disabled: false,
			extra_ro_binds: Vec::new(),
			forward_env: Vec::new(),
			set_env: Vec::new(),
		}
	}

	#[cfg(test)]
	pub(crate) fn disabled_for_tests(workdir: impl Into<PathBuf>) -> Self {
		Self {
			workdir: workdir.into(),
			network: None,
			network_supervisor: None,
			disabled: true,
			extra_ro_binds: Vec::new(),
			forward_env: Vec::new(),
			set_env: Vec::new(),
		}
	}

	/// Attach isolated outbound networking. The required hosts are
	/// backend-owned destinations such as the provider API and cannot
	/// be removed by operator configuration.
	pub fn with_network(
		mut self, config: SandboxNetworkConfig, required_hosts: Vec<String>,
	) -> Self {
		self.network = Some(SandboxNetworkLaunch { config, required_hosts });
		self
	}

	/// Select the trusted worker binary that supervises a networked
	/// sandbox. Production normally defaults to the current executable;
	/// callers that already pin a worker binary for a broker mount should
	/// use the same path here.
	pub fn with_network_supervisor(mut self, worker_binary: impl Into<PathBuf>) -> Self {
		self.network_supervisor = Some(worker_binary.into());
		self
	}

	/// Bind-mount `src` (a path on the host) read-only at `dst` (a path
	/// inside the sandbox). The two can be equal — that's the common
	/// case when surfacing a host install directly.
	pub fn bind_ro(mut self, src: impl Into<PathBuf>, dst: impl Into<PathBuf>) -> Self {
		self.extra_ro_binds.push((src.into(), dst.into()));
		self
	}

	/// Forward a non-secret env var into the sandbox. The value is looked up
	/// from the worker's own environment at `build()` time. Provider credentials
	/// must remain in a host-side broker and must never use this path.
	pub fn forward_env(mut self, name: &'static str) -> Self {
		self.forward_env.push(name);
		self
	}

	/// Set an env var to a caller-provided value inside the sandbox.
	/// This is useful when a backend accepts one env name but Loupe
	/// supports a compatibility alias at the worker boundary.
	pub fn set_env(mut self, name: &'static str, value: impl Into<OsString>) -> Self {
		self.set_env.push((name, value.into()));
		self
	}

	/// Locate `name` on the host PATH and bind-mount the install tree
	/// into the sandbox so the wrapped subprocess can `exec` it. The
	/// default sandbox only mounts system binaries, libraries, and a
	/// minimal allowlist of public `/etc` inputs. Anything installed in
	/// `~/.local/bin` (per-user installs, npm-global with non-root prefix,
	/// etc.) is invisible to the wrapped subprocess unless this method is
	/// called.
	///
	/// Resolves the entry point on PATH, follows the symlink chain
	/// to its canonical real path, and bind-mounts both the entry
	/// point and the canonical install directory read-only. Symlinked
	/// entry points are preserved by mounting their parent directory:
	/// binding the symlink path itself turns it into a regular file in
	/// the sandbox, which can break runtimes that resolve modules from
	/// the real package path.
	///
	/// Special-cases npm package layouts: when canonical lives inside
	/// a `node_modules/<scope>?/<pkg>/` tree, the outer `node_modules`
	/// root is mounted instead of just the entry point's parent dir.
	/// This is load-bearing for wrappers that load platform-specific
	/// optional deps via `require.resolve('@scope/pkg-platform')`.
	/// Depending on the package manager, those deps can be nested under
	/// the wrapper package or installed as siblings under the global
	/// `node_modules` root. Codex is the canonical example.
	pub fn allow_binary(self, name: &str) -> Result<Self> {
		let original =
			locate_on_path(name).ok_or_else(|| anyhow::anyhow!("`{name}` not found on PATH"))?;
		let canonical = std::fs::canonicalize(&original)
			.with_context(|| format!("canonicalizing {}", original.display()))?;

		let entrypoint_bind = entrypoint_bind_source(&original)?;
		let mut this = self.bind_ro(entrypoint_bind.clone(), entrypoint_bind);
		// Decide what to mount alongside the entry point.
		// Priority: directory canonical → that dir; npm package
		// detected → the node_modules root; else canonical's parent.
		let install_dir = if canonical.is_dir() {
			canonical
		} else if let Some(node_modules_root) = npm_node_modules_root(&canonical) {
			node_modules_root
		} else {
			canonical
				.parent()
				.ok_or_else(|| anyhow::anyhow!("canonical path has no parent"))?
				.to_path_buf()
		};
		this = this.bind_ro(install_dir.clone(), install_dir);
		Ok(this)
	}

	/// Build a `Command` for `program`. The command runs inside the
	/// sandbox; its `args()` should be appended by the caller as normal.
	/// Test-only disabled builders return a bare command rooted at the
	/// worktree.
	pub fn build(&self, program: &str) -> Command {
		if self.disabled {
			let mut cmd = Command::new(program);
			cmd.current_dir(&self.workdir);
			for (name, value) in &self.set_env {
				cmd.env(name, value);
			}
			return cmd;
		}

		let mut cmd = if let Some(network) = &self.network {
			let launcher = self.network_supervisor.clone().unwrap_or_else(|| {
				std::env::current_exe().unwrap_or_else(|_| PathBuf::from("loupe-worker"))
			});
			let mut cmd = Command::new(launcher);
			cmd.arg("sandbox-exec");
			cmd.arg("--network").arg(network.config.mode.as_str());
			for host in &network.required_hosts {
				cmd.arg("--required-host").arg(host);
			}
			for host in &network.config.allowlist {
				cmd.arg("--allow-host").arg(host);
			}
			cmd.arg("--").arg(BWRAP_BIN);
			cmd
		} else {
			Command::new(BWRAP_BIN)
		};
		cmd.env_clear();
		cmd.env("PATH", sandbox_path());
		cmd.arg("--die-with-parent");
		cmd.arg("--new-session");
		cmd.arg("--clearenv");

		// Load-bearing for rootless slirp/nft setup, and subtler than it
		// looks. The supervisor configures networking by entering the
		// *parent* of the sandbox's user namespace, because that is the
		// namespace owning the network namespace, and it holds full
		// capabilities there as its creator. That only works when
		// Bubblewrap nests two user namespaces: a privileged one for
		// setup and the one the sandbox ends up in. Bubblewrap nests them
		// only when setup needed privileges it then has to drop, which
		// here is mounting a fresh `/dev` below. Without that, the parent
		// is the supervisor's own namespace, re-entering it is `EINVAL`,
		// and every networked sandbox fails at startup.
		cmd.args(["--unshare-user", "--unshare-net"]);
		cmd.args(["--unshare-pid", "--unshare-ipc", "--unshare-uts"]);

		// Read-only system binaries and libraries. /lib and /lib64 are
		// platform-dependent, so bind whichever exists. Never bind all
		// of /etc: supported deployments store the worker identity there.
		for ro in ["/usr", "/lib", "/lib64", "/bin", "/sbin"] {
			if Path::new(ro).exists() {
				cmd.args(["--ro-bind-try", ro, ro]);
			}
		}

		add_minimal_system_binds(&mut cmd, self.network.is_some());

		// `--dev` is what makes Bubblewrap nest the second user namespace the
		// network supervisor depends on; see the note above `--unshare-user`.
		cmd.args(["--proc", "/proc", "--dev", "/dev"]);

		// Fresh tmpfs for /tmp and a new $HOME. *Must* come before
		// any extra_ro_binds that target paths inside /home/scanner —
		// bwrap processes args in order and a tmpfs mounted on top of
		// a prior bind hides it. Putting the tmpfs first lets caller
		// binds (e.g. ~/.claude.json → /home/scanner/.claude.json)
		// overlay the tmpfs and stay visible.
		cmd.args(["--tmpfs", "/tmp", "--tmpfs", "/home/scanner"]);
		cmd.args(["--setenv", "HOME", "/home/scanner"]);
		cmd.args(["--setenv", "TMPDIR", "/tmp"]);
		cmd.args(["--setenv", "PATH"]).arg(sandbox_path());

		// Caller-supplied read-only binds (binary install dirs, agent
		// config dirs, etc.). Use `--ro-bind-try` so a missing src
		// path is a no-op rather than a fatal — handy when binding an
		// optional auth dir that may or may not exist on every host.
		for (src, dst) in &self.extra_ro_binds {
			cmd.arg("--ro-bind-try").arg(src).arg(dst);
		}

		// Worktree: read-only.
		cmd.arg("--ro-bind").arg(&self.workdir).arg("/workdir");
		cmd.args(["--chdir", "/home/scanner"]);

		// Forwarded env vars. Skip those that aren't set on the host.
		for name in &self.forward_env {
			if let Some(value) = std::env::var_os(name) {
				cmd.arg("--setenv").arg(name).arg(value);
			}
		}
		for (name, value) in &self.set_env {
			cmd.arg("--setenv").arg(name).arg(value);
		}

		cmd.arg("--").arg(program);
		cmd
	}

	/// Convenience: build with full args + stdio piped, returning the
	/// fully prepared command for the caller to spawn.
	pub fn build_with_args<'a>(
		&self, program: &str, args: impl IntoIterator<Item = &'a str>,
	) -> Command {
		let mut cmd = self.build(program);
		for a in args {
			cmd.arg(a);
		}
		cmd
	}
}

fn sandbox_disabled() -> bool {
	let value = std::env::var_os(DISABLE_SANDBOX_ENV);
	sandbox_disabled_value(value.as_deref())
}

fn sandbox_disabled_value(value: Option<&OsStr>) -> bool {
	value.is_some_and(|value| {
		let value = value.to_string_lossy();
		if value.is_empty() {
			return false;
		}
		!matches!(value.to_ascii_lowercase().as_str(), "0" | "false" | "no" | "off")
	})
}

fn sandbox_path() -> String {
	std::env::var("PATH")
		.unwrap_or_else(|_| "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin".into())
}

fn add_minimal_system_binds(cmd: &mut Command, allow_network: bool) {
	// Bubblewrap creates parents for nested bind destinations, but the
	// top-level directory must exist first.
	cmd.args(["--dir", "/etc"]);
	for path in SANDBOX_SYSTEM_FILES {
		add_canonical_ro_bind(cmd, path);
	}
	if allow_network {
		for path in SANDBOX_NETWORK_FILES.iter().chain(SANDBOX_CA_PATHS) {
			add_canonical_ro_bind(cmd, path);
		}
		cmd.args(["--ro-bind", SANDBOX_RESOLV_CONF_PLACEHOLDER, "/etc/resolv.conf"]);
	}
}

fn add_canonical_ro_bind(cmd: &mut Command, destination: &str) {
	let Ok(source) = std::fs::canonicalize(destination) else {
		return;
	};
	// Resolve symlinks on the trusted side, then mount only the resolved
	// file or directory at its conventional sandbox path. This keeps a
	// systemd-resolved target usable without exposing its /run parent.
	cmd.arg("--ro-bind").arg(source).arg(destination);
}

/// If `path` lives inside a `node_modules/` tree, return the outer
/// `node_modules` directory.
/// Handles both unscoped (`node_modules/<pkg>/`) and scoped
/// (`node_modules/@scope/<pkg>/`) layouts. Returns `None` if `path`
/// isn't inside a `node_modules/`, or if the components after it
/// don't match an npm package shape.
///
/// Used by [`SandboxBuilder::allow_binary`] to make a global npm CLI
/// see both its own package and platform-specific optional deps. Some
/// npm installs keep those deps nested under the package; others hoist
/// them as siblings under the global `node_modules` root.
fn npm_node_modules_root(path: &Path) -> Option<PathBuf> {
	let components: Vec<_> = path.components().collect();
	// First (outermost) `node_modules` in the path. Outermost is
	// what we want: it covers both the wrapper package and any sibling
	// optional packages the wrapper resolves at runtime.
	let nm_idx = components.iter().position(|c| c.as_os_str() == "node_modules")?;
	let pkg_start = components.get(nm_idx + 1)?;
	let is_scoped = pkg_start.as_os_str().to_str().is_some_and(|s| s.starts_with('@'));
	let take = if is_scoped { nm_idx + 3 } else { nm_idx + 2 };
	if components.len() < take {
		return None;
	}
	let mut p = PathBuf::new();
	for c in &components[..=nm_idx] {
		p.push(c);
	}
	Some(p)
}

fn entrypoint_bind_source(original: &Path) -> Result<PathBuf> {
	if std::fs::symlink_metadata(original).map(|m| m.file_type().is_symlink()).unwrap_or(false) {
		original
			.parent()
			.ok_or_else(|| anyhow::anyhow!("PATH entry has no parent"))
			.map(Path::to_path_buf)
	} else {
		Ok(original.to_path_buf())
	}
}

/// PATH walk: return the first existing executable file matching
/// `name`. Mirrors what `execvp` would do — used by
/// [`SandboxBuilder::allow_binary`] to discover the host install of
/// an agent CLI without pulling in a `which`-style dep.
fn locate_on_path(name: &str) -> Option<PathBuf> {
	let path = std::env::var_os("PATH")?;
	for dir in std::env::split_paths(&path) {
		let candidate = dir.join(name);
		if candidate.is_file() {
			return Some(candidate);
		}
	}
	None
}

/// Validate that the host can run `bwrap` *with its full mount layout*,
/// not just `--version`. Useful in tests and as a smoke check before
/// the worker runs its first scan. Many container hosts have `bwrap`
/// installed but disable user namespaces, which makes any real
/// invocation fail; calling this once at startup surfaces that early
/// rather than mid-job.
pub fn smoketest(workdir: &Path, network: SandboxNetworkConfig) -> Result<()> {
	smoketest_with_builder(SandboxBuilder::new(workdir).with_network(network, Vec::new()))
}

#[doc(hidden)]
pub fn smoketest_with_supervisor(
	workdir: &Path, network: SandboxNetworkConfig, worker_binary: impl Into<PathBuf>,
) -> Result<()> {
	smoketest_with_builder(
		SandboxBuilder::new(workdir)
			.with_network(network, Vec::new())
			.with_network_supervisor(worker_binary),
	)
}

fn smoketest_with_builder(builder: SandboxBuilder) -> Result<()> {
	let mut cmd = builder.build("/bin/true");
	cmd.stdin(Stdio::null()).stdout(Stdio::null()).stderr(Stdio::piped());
	let output = cmd.as_std_mut().output().context("running bwrap smoketest")?;
	if !output.status.success() {
		let stderr = String::from_utf8_lossy(&output.stderr);
		anyhow::bail!("bwrap smoketest failed: {} ({stderr})", output.status);
	}
	Ok(())
}

#[cfg(test)]
mod tests {
	use std::io::Write;

	use super::*;
	use crate::test_env::in_env;

	fn bwrap_present() -> bool {
		std::process::Command::new(BWRAP_BIN)
			.arg("--version")
			.stdout(Stdio::null())
			.stderr(Stdio::null())
			.status()
			.map(|s| s.success())
			.unwrap_or(false)
	}

	#[test]
	fn npm_node_modules_root_picks_unscoped_package_dir() {
		let p = Path::new("/home/u/.local/lib/node_modules/foo/bin/foo.js");
		let root = npm_node_modules_root(p).unwrap();
		assert_eq!(root, Path::new("/home/u/.local/lib/node_modules"));
	}

	#[test]
	fn npm_node_modules_root_picks_scoped_package_dir() {
		// Scoped packages (`@openai/codex`) have one extra path
		// component vs. unscoped. Mount the outer node_modules dir so
		// optional native-binary deps work whether npm nests or hoists
		// them.
		let p = Path::new("/h/u/.local/lib/node_modules/@openai/codex/bin/codex.js");
		let root = npm_node_modules_root(p).unwrap();
		assert_eq!(root, Path::new("/h/u/.local/lib/node_modules"));
	}

	#[test]
	fn npm_node_modules_root_returns_none_outside_node_modules() {
		assert!(npm_node_modules_root(Path::new("/usr/local/bin/foo")).is_none());
		assert!(npm_node_modules_root(Path::new("/home/u/.local/share/claude/versions/1/claude"))
			.is_none());
	}

	#[test]
	fn npm_node_modules_root_handles_outermost_when_nested() {
		// A nested install (the wrapper itself nests its native-bin
		// dep under its own node_modules) — the *outermost*
		// node_modules is what we want, so the mount covers the
		// wrapper package and the nested tree.
		let p = Path::new(
			"/h/u/.local/lib/node_modules/@openai/codex/node_modules/@openai/codex-linux-x64/vendor/.../bin",
		);
		let root = npm_node_modules_root(p).unwrap();
		assert_eq!(root, Path::new("/h/u/.local/lib/node_modules"));
	}

	#[cfg(unix)]
	#[test]
	fn entrypoint_bind_source_preserves_symlinked_entrypoint_parent() {
		use std::os::unix::fs::symlink;

		let tmp = tempfile::tempdir().unwrap();
		let bin_dir = tmp.path().join("bin");
		let pkg_dir = tmp.path().join("lib/node_modules/@openai/codex/bin");
		std::fs::create_dir_all(&bin_dir).unwrap();
		std::fs::create_dir_all(&pkg_dir).unwrap();
		let target = pkg_dir.join("codex.js");
		std::fs::write(&target, "#!/usr/bin/env node\n").unwrap();
		symlink("../lib/node_modules/@openai/codex/bin/codex.js", bin_dir.join("codex")).unwrap();

		assert_eq!(entrypoint_bind_source(&bin_dir.join("codex")).unwrap(), bin_dir);
	}

	#[tokio::test]
	async fn build_runs_a_command_inside_the_sandbox() {
		if !bwrap_present() {
			eprintln!("skipping: bwrap not installed");
			return;
		}
		let tmp = tempfile::tempdir().unwrap();
		let mut cmd = SandboxBuilder::new(tmp.path()).build("/bin/sh");
		let out =
			cmd.arg("-c").arg("echo hello && pwd").output().await.expect("bwrap smoketest spawned");
		assert!(
			out.status.success(),
			"exit: {}, stderr: {}",
			out.status,
			String::from_utf8_lossy(&out.stderr)
		);
		let stdout = String::from_utf8_lossy(&out.stdout);
		assert!(stdout.contains("hello"), "stdout: {stdout}");
		assert!(
			stdout.contains("/home/scanner"),
			"should start outside the repository, got: {stdout}"
		);
	}

	#[tokio::test]
	async fn worktree_mount_is_read_only() {
		if !bwrap_present() {
			eprintln!("skipping: bwrap not installed");
			return;
		}
		let tmp = tempfile::tempdir().unwrap();
		// Plant a file the test can try to overwrite.
		let mut f = std::fs::File::create(tmp.path().join("readme")).unwrap();
		f.write_all(b"original").unwrap();

		let out = SandboxBuilder::new(tmp.path())
			.build("/bin/sh")
			.arg("-c")
			.arg("echo overwrite > /workdir/readme && echo OK || echo DENIED")
			.output()
			.await
			.expect("spawn");
		let stdout = String::from_utf8_lossy(&out.stdout);
		// The command itself must report DENIED — read-only mount.
		assert!(stdout.contains("DENIED"), "stdout: {stdout}");
		// And the original file on disk is unchanged.
		let after = std::fs::read_to_string(tmp.path().join("readme")).unwrap();
		assert_eq!(after, "original");
	}

	#[tokio::test]
	async fn tmp_is_fresh_per_invocation() {
		if !bwrap_present() {
			eprintln!("skipping: bwrap not installed");
			return;
		}
		let tmp = tempfile::tempdir().unwrap();
		// First run: drop a marker into /tmp.
		let out = SandboxBuilder::new(tmp.path())
			.build("/bin/sh")
			.arg("-c")
			.arg("echo marker > /tmp/m && cat /tmp/m")
			.output()
			.await
			.unwrap();
		assert!(out.status.success());
		assert!(String::from_utf8_lossy(&out.stdout).contains("marker"));

		// Second run: marker must be gone — /tmp is a fresh tmpfs.
		let out = SandboxBuilder::new(tmp.path())
			.build("/bin/sh")
			.arg("-c")
			.arg("test -f /tmp/m && echo LEAK || echo CLEAN")
			.output()
			.await
			.unwrap();
		let stdout = String::from_utf8_lossy(&out.stdout);
		assert!(stdout.contains("CLEAN"), "/tmp must be fresh between runs; got: {stdout}");
	}

	#[tokio::test]
	async fn unshare_net_blocks_outbound_connections() {
		if !bwrap_present() {
			eprintln!("skipping: bwrap not installed");
			return;
		}
		let tmp = tempfile::tempdir().unwrap();
		// `getent hosts` should fail without --share-net (no DNS).
		let out = SandboxBuilder::new(tmp.path())
			.build("/bin/sh")
			.arg("-c")
			.arg("getent hosts example.com >/dev/null 2>&1 && echo ALLOWED || echo BLOCKED")
			.output()
			.await
			.unwrap();
		let stdout = String::from_utf8_lossy(&out.stdout);
		assert!(stdout.contains("BLOCKED"), "net should be unshared; got: {stdout}");
	}

	#[test]
	fn disabled_sandbox_returns_bare_command() {
		// Force the test-only unwrapped path; no environment variable
		// can reach it.
		let mut b = SandboxBuilder::new("/tmp");
		b.disabled = true;
		let cmd = b.build("/bin/echo");
		assert_eq!(cmd.as_std().get_program(), "/bin/echo");
	}

	#[test]
	fn disable_sandbox_env_accepts_false_values() {
		for value in [None, Some(""), Some("0"), Some("false"), Some("no"), Some("off")] {
			assert!(
				!sandbox_disabled_value(value.map(OsStr::new)),
				"{value:?} should stay enabled"
			);
		}
		for value in ["1", "true", "yes", "on"] {
			assert!(sandbox_disabled_value(Some(OsStr::new(value))), "{value:?} should disable");
		}
	}

	#[test]
	fn startup_rejects_the_legacy_disable_request() {
		// Drive the probe itself, not just `ensure_sandbox_enabled`:
		// startup must reject the legacy request explicitly instead of
		// silently ignoring stale deployment configuration. The builder
		// independently guarantees that production commands always wrap.
		// Rejection happens before the `bwrap` spawn.
		if !in_env(
			"sandbox::tests::startup_rejects_the_legacy_disable_request",
			"disabled",
			&[(DISABLE_SANDBOX_ENV, Some("1".as_ref()))],
		) {
			return;
		}

		let result = probe_at_startup(false);

		let error = result.expect_err("worker must fail closed when sandboxing is disabled");
		assert!(
			error.to_string().contains(DISABLE_SANDBOX_ENV),
			"the startup error must name the variable the operator set: {error}",
		);
	}

	#[test]
	fn builder_ignores_the_legacy_sandbox_bypass_variable() {
		// `probe_at_startup` rejects the variable, so a builder that
		// still consults it is a second, silent way to lose isolation
		// — for anything constructed outside the startup path.
		if !in_env(
			"sandbox::tests::builder_ignores_the_legacy_sandbox_bypass_variable",
			"disabled",
			&[(DISABLE_SANDBOX_ENV, Some("1".as_ref()))],
		) {
			return;
		}

		let cmd = SandboxBuilder::new("/tmp").build("/bin/true");
		let program = cmd.as_std().get_program().to_string_lossy().into_owned();

		assert_eq!(
			program, BWRAP_BIN,
			"the builder must not unwrap the sandbox for a stray environment variable",
		);
	}

	#[test]
	fn agent_starts_outside_the_untrusted_repository() {
		let cmd = SandboxBuilder::new("/tmp").build("/bin/true");
		let args: Vec<String> =
			cmd.as_std().get_args().map(|arg| arg.to_string_lossy().into_owned()).collect();
		assert!(
			args.windows(2).any(|pair| pair == ["--chdir", "/home/scanner"]),
			"agent must not auto-load instructions from the repository root: {args:?}",
		);
	}

	#[test]
	fn sandbox_does_not_bind_the_host_etc_tree() {
		let cmd = SandboxBuilder::new("/tmp").build("/bin/true");
		let args: Vec<String> =
			cmd.as_std().get_args().map(|arg| arg.to_string_lossy().into_owned()).collect();

		assert!(
			!args.windows(3).any(|window| {
				matches!(window[0].as_str(), "--ro-bind" | "--ro-bind-try")
					&& window[1..] == ["/etc", "/etc"]
			}),
			"the sandbox must expose individual public system files, not the host /etc tree: {args:?}",
		);
	}

	#[tokio::test]
	async fn sandbox_hides_non_allowlisted_etc_files() {
		if !bwrap_present() || !Path::new("/etc/machine-id").exists() {
			eprintln!("skipping: bwrap or /etc/machine-id missing");
			return;
		}
		let workdir = tempfile::tempdir().unwrap();
		let out = SandboxBuilder::new(workdir.path())
			.build("/bin/sh")
			.arg("-c")
			.arg("test ! -e /etc/machine-id")
			.output()
			.await
			.expect("sandbox command should run");

		assert!(
			out.status.success(),
			"a non-allowlisted host /etc file remained visible inside the sandbox",
		);
	}

	#[cfg(unix)]
	#[test]
	fn system_file_bind_resolves_symlink_without_its_parent() {
		use std::os::unix::fs::symlink;

		let scratch = tempfile::tempdir().unwrap();
		let target = scratch.path().join("target");
		let link = scratch.path().join("link");
		std::fs::write(&target, "resolver data").unwrap();
		symlink(&target, &link).unwrap();
		let mut cmd = Command::new(BWRAP_BIN);
		add_canonical_ro_bind(&mut cmd, link.to_str().unwrap());
		let args: Vec<PathBuf> = cmd.as_std().get_args().map(PathBuf::from).collect();

		assert_eq!(args, [PathBuf::from("--ro-bind"), target, link]);
	}

	#[tokio::test]
	async fn bind_ro_under_tmpfs_home_remains_visible() {
		// Regression: bwrap processes args in order, so a tmpfs
		// emitted *after* a bind on a path inside that tmpfs will
		// hide the bind. We emit tmpfs first; this test pins that
		// ordering by binding a marker file into /home/scanner and
		// reading it back from inside the sandbox.
		if !bwrap_present() {
			eprintln!("skipping: bwrap not installed");
			return;
		}
		let workdir = tempfile::tempdir().unwrap();
		let marker_dir = tempfile::tempdir().unwrap();
		let marker_path = marker_dir.path().join("creds");
		std::fs::write(&marker_path, b"hello-from-host").unwrap();

		let out = SandboxBuilder::new(workdir.path())
			.bind_ro(marker_path, "/home/scanner/creds")
			.build("/bin/sh")
			.arg("-c")
			.arg("cat /home/scanner/creds")
			.output()
			.await
			.unwrap();
		assert!(
			out.status.success(),
			"exit: {}, stderr: {}",
			out.status,
			String::from_utf8_lossy(&out.stderr),
		);
		let stdout = String::from_utf8_lossy(&out.stdout);
		assert_eq!(stdout.trim(), "hello-from-host");
	}

	#[test]
	fn network_enabled_commands_use_a_private_namespace() {
		let cmd = SandboxBuilder::new("/tmp")
			.with_network(SandboxNetworkConfig::default(), Vec::new())
			.build("/bin/true");
		let args: Vec<String> =
			cmd.as_std().get_args().map(|s| s.to_string_lossy().into_owned()).collect();
		assert!(args.iter().any(|a| a == "sandbox-exec"), "args: {args:?}");
		assert!(args.iter().any(|a| a == "--unshare-user"), "args: {args:?}");
		// Bubblewrap only nests the second user namespace the supervisor
		// enters when setup took privileges it then dropped, and mounting
		// a fresh /dev is what does that here. Drop this and every
		// networked sandbox fails with EINVAL from nsenter.
		let dev = args.iter().position(|a| a == "--dev").unwrap_or_else(|| {
			panic!("network-enabled sandboxes must mount a fresh /dev: {args:?}")
		});
		assert_eq!(args[dev + 1], "/dev", "args: {args:?}");
		assert!(
			args.iter().any(|a| a == "--unshare-net"),
			"network-enabled sandboxes must use a private namespace: {args:?}",
		);
		assert!(
			!args.iter().any(|a| a == "--share-net"),
			"network-enabled sandboxes must not share the worker namespace: {args:?}",
		);
	}

	#[test]
	fn network_enabled_commands_take_their_resolver_from_the_supervisor() {
		let cmd = SandboxBuilder::new("/tmp")
			.with_network(SandboxNetworkConfig::default(), Vec::new())
			.build("/bin/true");
		let args: Vec<String> =
			cmd.as_std().get_args().map(|s| s.to_string_lossy().into_owned()).collect();

		// The supervisor rewrites this placeholder into a generated resolver
		// pointing at the slirp DNS forwarder. Binding the host's own
		// /etc/resolv.conf instead would name nameservers the sandbox's
		// private namespace cannot reach.
		let placeholder = args
			.iter()
			.position(|arg| arg == SANDBOX_RESOLV_CONF_PLACEHOLDER)
			.unwrap_or_else(|| panic!("resolver placeholder must be bound: {args:?}"));
		assert_eq!(args[placeholder - 1], "--ro-bind", "args: {args:?}");
		assert_eq!(args[placeholder + 1], "/etc/resolv.conf", "args: {args:?}");
		assert!(
			!SANDBOX_NETWORK_FILES.contains(&"/etc/resolv.conf"),
			"the host resolver must not be bound alongside the generated one",
		);
	}

	#[test]
	fn wrapped_command_starts_from_clear_environment() {
		if !in_env(
			"sandbox::tests::wrapped_command_starts_from_clear_environment",
			"secret",
			&[("LOUPE_SANDBOX_TEST_SECRET", Some("do-not-leak".as_ref()))],
		) {
			return;
		}

		let cmd = SandboxBuilder::new("/tmp").build("/bin/true");
		let args: Vec<String> =
			cmd.as_std().get_args().map(|s| s.to_string_lossy().into_owned()).collect();

		assert!(args.iter().any(|a| a == "--clearenv"), "args: {args:?}");
		assert!(args.windows(2).any(|w| w[0] == "--setenv" && w[1] == "PATH"), "args: {args:?}");
		assert!(!args.iter().any(|a| a == "LOUPE_SANDBOX_TEST_SECRET"), "args: {args:?}");
		assert!(!args.iter().any(|a| a == "do-not-leak"), "args: {args:?}");
	}

	#[tokio::test]
	async fn wrapped_command_hides_unforwarded_host_environment_from_proc() {
		if !bwrap_present() {
			eprintln!("skipping: bwrap not installed");
			return;
		}
		if !in_env(
			"sandbox::tests::wrapped_command_hides_unforwarded_host_environment_from_proc",
			"secret",
			&[(
				"LOUPE_SANDBOX_TEST_UNFORWARDED_SECRET",
				Some("do-not-leak-through-bwrap".as_ref()),
			)],
		) {
			return;
		}

		let tmp = tempfile::tempdir().unwrap();
		let out = SandboxBuilder::new(tmp.path())
			.build("/bin/sh")
			.arg("-c")
			.arg("grep -aFq do-not-leak-through-bwrap /proc/1/environ && echo LEAK || echo CLEAN")
			.output()
			.await
			.unwrap();
		assert!(out.status.success(), "sandbox failed: {}", String::from_utf8_lossy(&out.stderr),);
		let stdout = String::from_utf8_lossy(&out.stdout);
		assert!(
			stdout.contains("CLEAN"),
			"unforwarded host env leaked through /proc/1/environ: {stdout}",
		);
	}

	#[test]
	fn wrapped_command_isolates_controlling_terminal() {
		let cmd = SandboxBuilder::new("/tmp").build("/bin/true");
		let args: Vec<String> =
			cmd.as_std().get_args().map(|arg| arg.to_string_lossy().into_owned()).collect();

		assert!(
			args.iter().any(|arg| arg == "--new-session"),
			"sandbox must isolate the controlling terminal with --new-session: {args:?}",
		);
	}

	#[test]
	fn forward_env_explicitly_passes_allowlisted_values() {
		if !in_env(
			"sandbox::tests::forward_env_explicitly_passes_allowlisted_values",
			"forwarded",
			&[("LOUPE_SANDBOX_TEST_SECRET", Some("forwarded-value".as_ref()))],
		) {
			return;
		}

		let cmd =
			SandboxBuilder::new("/tmp").forward_env("LOUPE_SANDBOX_TEST_SECRET").build("/bin/true");
		let args: Vec<String> =
			cmd.as_std().get_args().map(|s| s.to_string_lossy().into_owned()).collect();

		assert!(
			args.windows(3).any(|w| {
				w[0] == "--setenv"
					&& w[1] == "LOUPE_SANDBOX_TEST_SECRET"
					&& w[2] == "forwarded-value"
			}),
			"args: {args:?}"
		);
	}

	#[test]
	fn set_env_passes_caller_provided_values() {
		let cmd = SandboxBuilder::new("/tmp")
			.set_env("LOUPE_SANDBOX_TEST_EXPLICIT", "explicit-value")
			.build("/bin/true");
		let args: Vec<String> =
			cmd.as_std().get_args().map(|s| s.to_string_lossy().into_owned()).collect();

		assert!(
			args.windows(3).any(|w| {
				w[0] == "--setenv"
					&& w[1] == "LOUPE_SANDBOX_TEST_EXPLICIT"
					&& w[2] == "explicit-value"
			}),
			"args: {args:?}"
		);
	}

	#[test]
	fn disabled_sandbox_sets_caller_provided_values() {
		let cmd = SandboxBuilder::disabled_for_tests("/tmp")
			.set_env("LOUPE_SANDBOX_TEST_EXPLICIT", "explicit-value")
			.build("/bin/true");

		assert!(cmd.as_std().get_envs().any(|(key, value)| {
			key == "LOUPE_SANDBOX_TEST_EXPLICIT" && value.is_some_and(|v| v == "explicit-value")
		}));
	}
}
